// import localFont from "next/font/local";
import "./globals.css";
import {Playfair_Display, Jacques_Francois_Shadow } from 'next/font/google'

const  playfairDisplay  = Playfair_Display({
  weight: ['400', '700'],
  subsets: ['latin'],
});
const jacquesFrancoisShadow = Jacques_Francois_Shadow({
  weight: '400', // Yeh font sirf ek weight me available hai
  subsets: ['latin'],
});
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <body className={`${playfairDisplay.className} ${jacquesFrancoisShadow.className}`}>
        {children}
      </body>
    </html>
  );
}
